### ISSUE TITLE
ConcurrentModificationException when ViewObservable.clicks().take(1)

### ISSUE THREAD

**Issue by shinyaohira** [ReactiveX/RxAndroid#158]
I would like to do something just one time when users tap a button. Here is my code:

```java
ViewObservable.clicks(button)
                .take(1)
                .subscribe(/* do something */);
```

but I got ConcurrentModificationException.

```
java.util.ConcurrentModificationException
            at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
            at rx.android.view.OnSubscribeViewClick$CompositeOnClickListener.onClick(OnSubscribeViewClick.java:78)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
```

**Comment by iyotetsuya** [comment]
try this, it works for me.
```java 
ViewObservable.clicks(button)
    .observeOn(AndroidSchedulers.mainThread())
    .take(1)
    .subscribe(/* do something */);
```

**Comment by JakeWharton** [comment]
This is fixed in https://github.com/JakeWharton/RxBinding but per #172 this won't be going into RxAndroid core. We have removed the view binding observables for the next release.
