### ISSUE TITLE
CompositeException Behavior

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxAndroid#21]
There are possibly improvements that need to be made specific to Android related to `CompositeException`. 

History of the discussion and work on this can be found at https://github.com/ReactiveX/RxJava/issues/1405

**Comment by gderaco** [comment]
The reason of the exception (in my case) is this line in SafeSubscriber.java line 174
`throw new OnErrorFailedException("Error occurred when trying to propagate error to Observer.onError", new CompositeException(Arrays.asList(e, e2)));
`
It throws exception because e2 is null. 
In my case, the Throwable I pass to `onError()` method is `android.os.NetworkOnMainThreadException`

I think a buffer solution would be checking if e2 is null.

I'm using rxandroid 0.23. Hope this can help.

**Comment by JakeWharton** [comment]
`UnknownHostException`'s trace is never logged, FYI, as you can see in the source of `Log.java`. Is there still an issue beyond that?

**Comment by malachid** [comment]
I was getting a similar error whenever I used RetrofitError.getBody inside RxJava Subscriber.onError. Turns out it was being caused by the getBody call itself throwing an exception.  Since initCause, setStackTrace, readObject, and addSuppressed all internally throw exceptions - maybe it's related.

**Comment by farmazon3000** [comment]
I think this issue is mentioned here http://stackoverflow.com/questions/24860942/observer-onerror-firing-off-inconsistently.

**Comment by tomrozb** [comment]
@farmazon3000 you're right. I'm not sure it still happens in the latest version of Rx, can somebody confirm?

**Comment by farmazon3000** [comment]
I'm using
```
compile 'io.reactivex:rxjava:1.0.12'
compile 'io.reactivex:rxandroid:0.24.0'
```
and it does happen.

**Comment by dlew** [comment]
Those aren't the latest versions of RxJava and RxAndroid. The latest are:

```gradle
compile 'io.reactivex:rxjava:1.0.14'
compile 'io.reactivex:rxandroid:1.0.1'
```

**Comment by lunf** [comment]
I am on the latest version

'  E/AndroidRuntime: java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
  E/AndroidRuntime:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
  E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
  E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
  E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
  E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001)
  E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
  E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
  E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
  E/AndroidRuntime:  Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
  E/AndroidRuntime:     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201)
  E/AndroidRuntime:     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
  E/AndroidRuntime:     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:137)
  E/AndroidRuntime:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208)
  E/AndroidRuntime:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
  E/AndroidRuntime:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733) 
  E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
  E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136) 
  E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001) 
  E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
  E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
  E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
  E/AndroidRuntime:  Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
  E/AndroidRuntime:     at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:201) 
  E/AndroidRuntime:     at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111) 
  E/AndroidRuntime:     at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:137) 
  E/AndroidRuntime:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208) 
  E/AndroidRuntime:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170) 
  E/AndroidRuntime:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
  E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733) 
  E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
  E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136) 
  E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001) 
  E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
  E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515) 
  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
  E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
  E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
  E/AndroidRuntime:  Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
  E/AndroidRuntime:     at crittercism.android.bk.a(Unknown Source)
  E/AndroidRuntime:     at crittercism.android.bk.<init>(Unknown Source)
  E/AndroidRuntime:     at crittercism.android.az.a(Unknown Source)
  E/AndroidRuntime:     at crittercism.android.ay.uncaughtException(Unknown Source)'

**Comment by dimsuz** [comment]
Looks like it has nothing to do with RxAndroid. Your app's code threw an exception (most likely in your onError handler):

```
E/AndroidRuntime:     at crittercism.android.bk.a(Unknown Source)
E/AndroidRuntime:     at crittercism.android.bk.<init>(Unknown Source)
E/AndroidRuntime:     at crittercism.android.az.a(Unknown Source)
E/AndroidRuntime:     at crittercism.android.ay.uncaughtException(Unknown Source)
```

**Comment by malachid** [comment]
I just got it again (this time because I had a TextInputLayout without a child EditText) - but at least I knew what to look for.  It would be nice if my own code showed up in the stack trace somewhere.  Without that it turns out to be much harder to track down. 

Key though - it's always because your onError is calling something that is throwing an error of some kind (may be runtime, error, etc - not necessarily a compile time exception).

**Comment by JakeWharton** [comment]
This issue is old, and has no clear action to take. The most recent comments are normal errors being incorrectly attributed to this issue. As far as I can tell CE is now behaving in an acceptable manner and even if it wasn't this isn't the project which could change it.

**Comment by tommyd3mdi** [comment]
We're experiencing this issue also in our code. Clearly, its an application issue where _somewhere_ the `onError` implementation throws. However, RxJava makes it hard to point out _where_ exactly this happens, because `CompositeException` swallows `onError`s exception iff it shares a cause with the original throwable. Here is the code:

                List<Throwable> listOfCauses = getListOfCauses(e);
                // check if any of them have been seen before
                for(Throwable child : listOfCauses) {
                    if (seenCauses.contains(child)) {
                        // already seen this outer Throwable so skip
                        e = new RuntimeException("Duplicate found in causal chain so cropping to prevent loop ...");
                        continue;
                    }
                    seenCauses.add(child);
                }

So, say the chain throws  `e1` and your code in `onError` throws `e2` _while_ being "somehow" a good citizen and remembers the original `e1` as cause. `e2` will then completely get evicted / replaced with a new `RuntimeException` telling us "Duplicate found in causal chain so cropping to prevent loop ...". If you then work with Crashlytics, you will not see anything beside this very runtime exception (even without the exception message, since this is not part of Crashlytics' output for causes for whatever reason). And you will not see anything on logcat, because the exception chain is already way too long.

**Comment by JakeWharton** [comment]
Can we create a very small sample (preferably without using anything
Android-specific) that reproduces the problem?

**Comment by tommyd3mdi** [comment]
Using rxjava 1.1.1 - given this:

    public class Main {
        public static void main(String[] args) {
    	    Observable
                    .error(new IllegalArgumentException("illegal argument"))
                    .subscribe(
                            success -> {},
                            error -> {
                                throw new IllegalStateException("illegal state exception", error); // Main.java, line 13
                            }
                    );
        }
    }

I see this:

    Exception in thread "main" rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
    	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
    	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    	at rx.Observable$ThrowObservable$1.call(Observable.java:10200)
    	at rx.Observable$ThrowObservable$1.call(Observable.java:10190)
    	at rx.Observable.subscribe(Observable.java:8407)
    	at rx.Observable.subscribe(Observable.java:8374)
    	at rx.Observable.subscribe(Observable.java:8178)
    	at biz.thomaskeller.rxandroid_21.Main.main(Main.java:10)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
    	... 13 more
    Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
    	at rx.exceptions.CompositeException.getCause(CompositeException.java:96)
    	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:707)
    	at java.lang.Throwable.printStackTrace(Throwable.java:667)
    	at java.lang.Throwable.printStackTrace(Throwable.java:643)
    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1061)
    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
    	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
    Caused by: java.lang.IllegalArgumentException: illegal argument
    	at biz.thomaskeller.rxandroid_21.Main.main(Main.java:8)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
    	at rx.exceptions.CompositeException.getCause(CompositeException.java:112)
    	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:707)
    	at java.lang.Throwable.printStackTrace(Throwable.java:667)
    	at java.lang.Throwable.printStackTrace(Throwable.java:643)
    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1061)
    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
    	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)

whereas given this:

    public class Main {
        public static void main(String[] args) {
    	    Observable
                    .error(new IllegalArgumentException("illegal argument"))
                    .subscribe(
                            success -> {},
                            error -> {
                                throw new IllegalStateException("illegal state exception");  // Main.java, line 13
                            }
                    );
        }
    }

I see this:

    Exception in thread "main" rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
    	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:192)
    	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    	at rx.Observable$ThrowObservable$1.call(Observable.java:10200)
    	at rx.Observable$ThrowObservable$1.call(Observable.java:10190)
    	at rx.Observable.subscribe(Observable.java:8407)
    	at rx.Observable.subscribe(Observable.java:8374)
    	at rx.Observable.subscribe(Observable.java:8178)
    	at biz.thomaskeller.rxandroid_21.Main.main(Main.java:10)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
    	... 13 more
    Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
    	at rx.exceptions.CompositeException.getCause(CompositeException.java:96)
    	at java.lang.Throwable.printEnclosedStackTrace(Throwable.java:707)
    	at java.lang.Throwable.printStackTrace(Throwable.java:667)
    	at java.lang.Throwable.printStackTrace(Throwable.java:643)
    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1061)
    	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
    	at java.lang.Thread.dispatchUncaughtException(Thread.java:1952)
    Caused by: java.lang.IllegalArgumentException: illegal argument
    	at biz.thomaskeller.rxandroid_21.Main.main(Main.java:8)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
    Caused by: java.lang.IllegalStateException: illegal state exception
    	at biz.thomaskeller.rxandroid_21.Main.lambda$main$1(Main.java:13)
    	at biz.thomaskeller.rxandroid_21.Main$$Lambda$2/664223387.call(Unknown Source)
    	at rx.Observable$28.onError(Observable.java:8187)
    	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
    	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
    	at rx.Observable$ThrowObservable$1.call(Observable.java:10200)
    	at rx.Observable$ThrowObservable$1.call(Observable.java:10190)
    	at rx.Observable.subscribe(Observable.java:8407)
    	at rx.Observable.subscribe(Observable.java:8374)
    	at rx.Observable.subscribe(Observable.java:8178)
    	at biz.thomaskeller.rxandroid_21.Main.main(Main.java:10)
    	... 5 more

**Comment by tommyd3mdi** [comment]
Hrm... but there seems to be more - because none of my actual crashes point me really at `CompositeException.java:112`, where the actual cause is replaced with the pseudo cause that crops the chain, still, I always only see the "upstream" exception.

**Comment by paramsen** [comment]
As a note, this seems to be fixed in https://github.com/ReactiveX/RxJava/pull/3977 and included in RxJava version 1.1.6.

**Comment by hqzxzwb** [comment]
I encountered the same problem recently. I think the problem here is that error collecting SDKs (crashlytics, umeng, etc.) do more than `printStackTrace`. They go through the causal chain and print stack trace of every `Throwable` in it. But the cause of `CompositeException`, as I see from source code, has already been included in its own `printStackTrace` implementation. So the work these SDKs do is actually a duplication of CompositeException's `printStackTrace`.

**Comment by AnnKrepchenko** [comment]
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.0.1'

**Comment by domisafonov** [comment]
The issue seems to still be there in rxjava 2.1.12, rxandroid 2.1.0.
No cause is left in crashlytics:
`io.reactivex.exceptions.CompositeException: 
  at io.reactivex.internal.observers.ConsumerSingleObserver.onError (ConsumerSingleObserver.java:49)
  at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onError (SingleDoOnSubscribe.java:86)
  at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run (SingleObserveOn.java:79)
  at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run (HandlerScheduler.java:119)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)`
