### ISSUE TITLE
NoClassDefFoundError: rx/Observable. Crashes on request to Retrofit

### ISSUE THREAD

**Issue by wlsc** [ReactiveX/RxAndroid#263]
Hello!

RxAndroid/RxJava crashes while trying to request to API (Retrofit) on Galaxy Nexus 4.3 (JWR66Y).

Multi Dex is enabled. Android Studio 1.5.1. Already did clean/rebuild etc. Nothing works on Galaxy Nexus! Did tests on Nexus 5 (6.0.1) => works

Could anybody give me a hint?

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                 java.lang.NoClassDefFoundError: rx/Observable
                                                                                                     at $Proxy0.loginUser(Native Method)
                                                                                                     at <PACKAGE>.controller.login.LoginControllerImpl.doLogin(LoginControllerImpl.java:101)
                                                                                                     at <PACKAGE>.presenter.login.LoginPresenterImpl.attemptLogin(LoginPresenterImpl.java:82)
                                                                                                     at d<PACKAGE>.activity.LoginActivity.onUserLogin(LoginActivity.java:255)
                                                                                                     at <PACKAGE>.activity.LoginActivity$$ViewBinder$2.doClick(LoginActivity$$ViewBinder.java:36)
                                                                                                     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                                     at android.view.View.performClick(View.java:4240)
                                                                                                     at android.view.View$PerformClick.run(View.java:17721)
                                                                                                     at android.os.Handler.handleCallback(Handler.java:730)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                                                     at android.os.Looper.loop(Looper.java:137)
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.Observable" on path: DexPathList[[zip file "/data/app/<PACKAGE>-1.apk"],nativeLibraryDirectories=[/data/app-lib/<PACKAGE>-1, /vendor/lib, /system/lib]]
                                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
                                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                                                     at $Proxy0.loginUser(Native Method) 
                                                                                                     at <PACKAGE>.controller.login.LoginControllerImpl.doLogin(LoginControllerImpl.java:101) 
                                                                                                     at <PACKAGE>.presenter.login.LoginPresenterImpl.attemptLogin(LoginPresenterImpl.java:82) 
                                                                                                     at <PACKAGE>.activity.LoginActivity.onUserLogin(LoginActivity.java:255) 
                                                                                                     at <PACKAGE>.activity.LoginActivity$$ViewBinder$2.doClick(LoginActivity$$ViewBinder.java:36) 
                                                                                                     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
                                                                                                     at android.view.View.performClick(View.java:4240) 
                                                                                                     at android.view.View$PerformClick.run(View.java:17721) 
                                                                                                     at android.os.Handler.handleCallback(Handler.java:730) 
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:92) 
                                                                                                     at android.os.Looper.loop(Looper.java:137) 
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                                     at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by dlew** [comment]
This looks like a multidex issue where you aren't including `rx.Observable` in the primary dex file.

**Comment by wlsc** [comment]
Thank you for your hint. I have found the problem with this -> I had no entry in Manifest file for MultiDex support. Now it is working also on Galaxy Nexus with Android < 5.0!

have a nice day!
