### ISSUE TITLE
I use rxbus，if I send many object on a veary little time

### ISSUE THREAD

**Issue by xiaogu-space** [ReactiveX/RxAndroid#320]
```
 FATAL EXCEPTION: main
                                                               Process: com.dituwuyou, PID: 20194
                                                               java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                                   at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:112)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                Caused by: rx.exceptions.OnErrorNotImplementedException: PublishSubject: could not emit value due to lack of requests
                                                                   at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
                                                                   at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
                                                                   at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
                                                                   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:152)
                                                                   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:276)
                                                                   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
                                                                   at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
                                                                   at android.os.Handler.handleCallback(Handler.java:739) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                   at android.os.Looper.loop(Looper.java:148) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                Caused by: rx.exceptions.MissingBackpressureException: PublishSubject: could not emit value due to lack of requests
                                                                   at rx.subjects.PublishSubject$PublishSubjectProducer.onNext(PublishSubject.java:308)
                                                                   at rx.subjects.PublishSubject$PublishSubjectState.onNext(PublishSubject.java:220)
                                                                   at rx.subjects.PublishSubject.onNext(PublishSubject.java:73)
                                                                   at rx.observers.SerializedObserver.onNext(SerializedObserver.java:92)
                                                                   at rx.subjects.SerializedSubject.onNext(SerializedSubject.java:67)
                                                                   at com.dituwuyou.widget.rxjava.RxBus.send(RxBus.java:29)
                                                                   at com.dituwuyou.joint.CoorSocketService.messageReceived(CoorSocketService.java:51)
                                                                   at com.dituwuyou.fayeclient.FayeClient.parseFayeMessage(FayeClient.java:535)
                                                                   at com.dituwuyou.fayeclient.FayeClient.onMessage(FayeClient.java:390)
                                                                   at com.dituwuyou.fayeclient.HybiParser.emitFrame(HybiParser.java:304)
                                                                   at com.dituwuyou.fayeclient.HybiParser.start(HybiParser.java:130)
                                                                   at com.dituwuyou.fayeclient.WebSocketClient$1.run(WebSocketClient.java:119)
                                                                   at java.lang.Thread.run(Thread.java:818)]([url](url))
```

**Comment by xiaogu-space** [comment]
OK,It's my error

**Comment by tysheng** [comment]
i got the same error too, how did you solve it?
