### ISSUE TITLE
IllegalArgumentException: delay < 0: -237000000

### ISSUE THREAD

**Issue by PaulWoitaschek** [ReactiveX/RxAndroid#346]
I received a crash after updating to RxJava 2.0.0

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:113)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.IllegalArgumentException: delay < 0: -237000000
	at io.reactivex.android.schedulers.HandlerScheduler$HandlerWorker.schedule(HandlerScheduler.java:60)
	at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:307)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
```

**Comment by samueltardieu** [comment]
I have the same issue when using `Flowable.interval` on `AndroidSchedulers.mainThread()`, or `schedulePeriodically` on this scheduler. I do not have the problem when using `Schedulers.computation()` for example.

See https://github.com/cgeo/cgeo/issues/6087 for an example of this bug.

**Comment by PaulWoitaschek** [comment]
I'm receiving many many crashes of this type and bad user reviews. Can I do anything to speed up the fixing of this?

**Comment by JakeWharton** [comment]
Create a failing test case with a fix and send a PR.

**Comment by akarnokd** [comment]
Looks like your periodic task runs too long and the next round should have happened 237 milliseconds ago.

Otherwise, the `Scheduler` spec states that negative values should be considered non-delayed runs:
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Scheduler.java#L196
https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/Scheduler.java#L215

https://github.com/ReactiveX/RxAndroid/blob/2.x/rxandroid/src/main/java/io/reactivex/android/schedulers/HandlerScheduler.java#L31

``` java
    @Override
    public Disposable scheduleDirect(Runnable run, long delay, TimeUnit unit) {
        if (run == null) throw new NullPointerException("run == null");
        // if (delay < 0) throw new IllegalArgumentException("delay < 0: " + delay);
        if (unit == null) throw new NullPointerException("unit == null");

        run = RxJavaPlugins.onSchedule(run);
        ScheduledRunnable scheduled = new ScheduledRunnable(handler, run);
        handler.postDelayed(scheduled, unit.toMillis(Math.max(0L, delay)));
        return scheduled;
    }
```

**Comment by JakeWharton** [comment]
Fix merged. Release soon.

**Comment by korenivan** [comment]
?

**Comment by korenivan** [comment]
Release soon ?

**Comment by PaulWoitaschek** [comment]
It was released in december
