### ISSUE TITLE
Monkey testing throw AndroidRuntime EXCEPTION: java.lang.NullPointerException: onNext called with null. Null values are generally not allowed in 2.x operators and sources.

### ISSUE THREAD

**Issue by gavinliu** [ReactiveX/RxAndroid#370]
```
 java.lang.NullPointerException: onNext called with null. Null values are generally not allowed in 2.x operators and sources.
   at io.reactivex.internal.operators.observable.ObservableCreate$a.onNext(SourceFile:63)
   at mypackage$3$1.subscribe(VideoRepository.java:161)
   at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
   at io.reactivex.Observable.subscribe(Observable.java:10179)
   at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:39)
   at io.reactivex.Observable.subscribe(Observable.java:10179)
   at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
   at io.reactivex.Scheduler$1.run(Scheduler.java:134)
   at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
   at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)
```

```
Observable.create(new ObservableOnSubscribe<T>(){
    public void subscribe(ObservableEmitter<T> e) throws Exception {
        ...
        if (e != null) e.onNext(null);
    }
});
```

**Comment by JakeWharton** [comment]
`e` will never be `null` so remove that check. You cannot send `null` through an RxJava 2 stream. Read https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#nulls.

**Comment by gavinliu** [comment]
I find the source code that has try-catch. Why it is crushed ? 

> io.reactivex.internal.operators.observable.ObservableCreate#subscribeActual
```
        try {
            source.subscribe(parent);
        } catch (Throwable ex) {
            Exceptions.throwIfFatal(ex);
            parent.onError(ex);
        }
```

I try to write it like :

```
Observable.create(new ObservableOnSubscribe<T>(){
    public void subscribe(ObservableEmitter<T> e) throws Exception {
        T t = getT();

        if (t != null) {
            e.onError(new NullPointerException());
        } else {
            e.onNext(t);
        }
    }
});
```
The same will be throw ``AndroidRuntime EXCEPTION``


```
04-11 17:13:49.254 11054 12281 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-2
04-11 17:13:49.254 11054 12281 E AndroidRuntime: Process: mypackage, PID: 11054
04-11 17:13:49.254 11054 12281 E AndroidRuntime: java.lang.NullPointerException
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at mypackagea$2$1.a(SourceFile:94)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.internal.e.a.b.b(SourceFile:40)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.c.a(SourceFile:10179)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.internal.e.a.c.b(SourceFile:39)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.c.a(SourceFile:10179)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.internal.e.a.e$1.run(SourceFile:39)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.h$1.run(SourceFile:134)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.internal.g.f.run(SourceFile:59)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at io.reactivex.internal.g.f.call(SourceFile:51)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-11 17:13:49.254 11054 12281 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
```
