### ISSUE TITLE
An exception , Animators may only be run on Looper threads

### ISSUE THREAD

**Issue by 0xByteLeon** [ReactiveX/RxAndroid#371]
`<io.reactivex.exceptions.OnErrorNotImplementedException: Animators may only be run on Looper threads
                                                                          at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
                                                                          at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
                                                                          at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:72)
                                                                          at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:62)
                                                                          at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
                                                                          at io.reactivex.internal.operators.observable.ObservableDelay$DelayObserver$1.run(ObservableDelay.java:84)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:1069)
                                                                          at android.animation.ValueAnimator.start(ValueAnimator.java:1117)
                                                                          at cn.bingoogolapple.refreshlayout.BGARefreshLayout.changeRefreshHeaderViewToZero(BGARefreshLayout.java:770)
                                                                          at cn.bingoogolapple.refreshlayout.BGARefreshLayout.beginRefreshing(BGARefreshLayout.java:723)
                                                                          at com.proton.carepatchecg.fragment.MsgFragment.lambda$setBgaRefreshLayout$1(MsgFragment.java:163)
                                                                          at com.proton.carepatchecg.fragment.MsgFragment$$Lambda$4.accept(Unknown Source)
                                                                          at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:59)
                                                                          at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111) 
                                                                          at io.reactivex.internal.operators.observable.ObservableDelay$DelayObserver$1.run(ObservableDelay.java:84) 
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59) 
                                                                          at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51) 
                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) >`

**Comment by JakeWharton** [comment]
Your starting an animation in doOnNext that isn't running on the main thread. This has nothing to do with RxAndroid and is instead a programming error. Ensure that when you are touching the UI in a side-effect of your stream that you are observing events on the main thread. You need to have observeOn(mainThread()) before your side-effect operators.

**Comment by JakeWharton** [comment]
If you want to create a sample we can show you how to fix it, but it's not a bug in this library and GitHub issues are for bugs and feature requests and not discussion or help. StackOverflow is a much better forum for those.

**Comment by 0xByteLeon** [comment]
Thanks! But I don't know why,
this is normally code ：
`<Observable.just(1)
                .delay(1, TimeUnit.SECONDS)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(integer -> mBgaMsg.beginRefreshing());>` 

this is wrong code :
`< Observable.just(1)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .delay(1, TimeUnit.SECONDS)
                .subscribe(integer -> mBgaMsg.beginRefreshing());>` 

I can't understand !

**Comment by JakeWharton** [comment]
Drop `observeOn` and use `delay(1, SECONDS, mainThread())`

**Comment by JakeWharton** [comment]
The documentation for `delay` speaks about how it uses the `computation()` scheduler by default

**Comment by 0xByteLeon** [comment]
Thanks!
