### ISSUE TITLE
OutOfMemory issue with buffer method

### ISSUE THREAD

**Issue by gyorgygabor** [ReactiveX/RxAndroid#372]
Hi,

I want to collect my emitted items into a list with buffer(int count). I put  .buffer(Integer.MAX_VALUE) to get the whole list in one piece and I get the following error:

```java
UI crashed due to uncaught exception.
                                                                                             java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
                                                                                                 at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
                                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                                              Caused by: java.lang.OutOfMemoryError: java.lang.Object[] of length 2147483647 would overflow
```

**Comment by akarnokd** [comment]
*(I'm sure Jake would/will say this is not an issue with RxAndroid...)*

That `buffer()` operator is there to buffer into multiple lists each no longer than the specified size. This size amount is used for specifying the capacity on the underlying `ArrayList` as well thus an overly large amout may result in OOM. You are probably looking for the `toList` operator which collects all values into a single `List`.

**Comment by gyorgygabor** [comment]
The **toList()** does not emit the collection like **buffer()**

**Comment by akarnokd** [comment]
I recommend asking this question on StackOverflow where you specify what source you are using and why do you want to buffer with that large amount.
