### ISSUE TITLE
Exception when destroying HolderActivity

### ISSUE THREAD

**Issue by JamesMcIntosh** [ReactiveX/RxAndroid#380]
When using the v7:25.3.1 app compat libraries I get the following exception when focus is returned back to the original activity.

```
java.lang.RuntimeException: Unable to destroy activity {com.myproject.mobile.android/rx_activity_result2.HolderActivity}: java.lang.IllegalStateException: Fragment has not been attached yet.
     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5061)
     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5084)
     at android.app.ActivityThread.access$1700(ActivityThread.java:221)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1853)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:158)
     at android.app.ActivityThread.main(ActivityThread.java:7224)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
  Caused by: java.lang.IllegalStateException: Fragment has not been attached yet.
     at android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java:2154)
     at android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java:704)
     at rx_activity_result2.RxActivityResult$Builder.getTargetFragment(RxActivityResult.java:146)
     at rx_activity_result2.RxActivityResult$Builder.getTargetFragment(RxActivityResult.java:148)
     at rx_activity_result2.RxActivityResult$Builder.access$100(RxActivityResult.java:50)
     at rx_activity_result2.RxActivityResult$Builder$3.response(RxActivityResult.java:127)
     at rx_activity_result2.HolderActivity.onDestroy(HolderActivity.java:98)
     at android.app.Activity.performDestroy(Activity.java:7102)
     at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1170)
     at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5039)
     at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5084) 
     at android.app.ActivityThread.access$1700(ActivityThread.java:221) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1853) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:158) 
     at android.app.ActivityThread.main(ActivityThread.java:7224) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```
The problem stems from lazy creation of the fragment manager in the new library release.

I had to also address some of my own code which made use of fragment.getChildFragmentManager().getFragments() to check if the fragment isAdded() before requesting a child fragment manager.

Updating the line 137 in RxActivityResult should fix the problem.

```
if(fragment != null && fragment.getChildFragmentManager() != null) {

to

if(fragment != null && fragment.isAdded() && fragment.getChildFragmentManager() != null) {
```

**Comment by JakeWharton** [comment]
RxActivityResult is not from this library.
