### ISSUE TITLE
    java.lang.NoClassDefFoundError: io.reactivex.Flowable

### ISSUE THREAD

**Issue by qiuyudong** [ReactiveX/RxAndroid#386]
when I used   compile 'io.reactivex.rxjava2:rxjava:2.0.5'  it works, and when I used  compile files('libs/rxjava-2.0.5.jar') it was wrong 
The wrong information is these

                                                                             
                                                                               java.lang.NoClassDefFoundError: io.reactivex.Flowable
                                                                                   at com.jakewharton.retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory.get(RxJava2CallAdapterFactory.java:90)
                                                                                   at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:220)
                                                                                   at retrofit2.Retrofit.callAdapter(Retrofit.java:204)
                                                                                   at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:234)
                                                                                   at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:161)
                                                                                   at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:169)
                                                                                   at retrofit2.Retrofit$1.invoke(Retrofit.java:146)
                                                                                   at java.lang.reflect.Proxy.invoke(Proxy.java:397)
                                                                                   at $Proxy0.get(Unknown Source)

How can I do to use compile files,  thank you.

**Comment by JakeWharton** [comment]
This is not an issue related to RxAndroid. You should ask on StackOverflow since it's really about your build setup and only happens to use RxJava as the target library.

**Comment by huangruiLearn** [comment]
i also meet the issue ,  how did u deal with the issue
