### ISSUE TITLE
Caused by java.lang.IndexOutOfBoundsException: Index: 1, Size: 0

### ISSUE THREAD

**Issue by tarunkonda123** [ReactiveX/RxAndroid#448]
Caused by java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       a XXX.subscribeActual(Unknown Source:259)
       at io.reactivex.Observable.subscribe(Unknown Source:14)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(Unknown Source:6)
       at io.reactivex.Scheduler$DisposeTask.run(Unknown Source:9)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by JakeWharton** [comment]
There is no RxAndroid in this stacktrace nor any real information at all. You can post to RxJava if you believe this is a bug, but you'll need to provide more information about what triggered the problem.
