### ISSUE TITLE
Getting null exception error in production but working in debug mode. 

### ISSUE THREAD

**Issue by iamkdblue** [ReactiveX/RxAndroid#533]
I am getting an error in production but working in debug mode. 

Code:-
```
compositeDisposable.add(Observable.range(0, Integer.MAX_VALUE)
                // Get each page in order.
                .concatMap(integer -> {
                    return apiInterface.postGetFeed(membersIds, lastFeedId);
                })
                // Take every result up to and including the one where the next page index is null.
                .takeUntil(result -> {
                    if(!result.getData().isEmpty())
                    lastFeedId = result.getData().get(result.getData().size() - 1).getId();
                    return result.getData().isEmpty();
                })
                .map(FeedResponse::getData)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(new DisposableObserver<List<Feed>>() {
                               @Override
                               public void onNext(List<Feed> feeds) {
                                   Log.d("feed", "" + feeds);
                                   memberDatabaseRepository.insertMemberList(feeds, lastFeedId);

                               }

                               @Override
                               public void onError(Throwable e) {
                                   //error getting here
                                   Log.d("feed", "error " + e.getMessage());

                               }

                               @Override
                               public void onComplete() {
                                   memberDatabaseRepository.getAllFeed(FeedFragment.this);
                                   shimmerViewContainerFeed.stopShimmer();
                                   shimmerViewContainerFeed.setVisibility(View.GONE);
                               }
                           }
                ));
```

Error : 

2019-05-16 18:57:16.113 16757-16757/com.fitphilia.treadmill.trainer D/feed: error throw with null exception
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err: java.lang.NullPointerException: throw with null exception
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at c.e.a.a.g.r.a(Unknown Source:1)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at c.e.a.a.g.a.test(Unknown Source:4)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.r$a.a(Unknown Source:12)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.f.d.a(Unknown Source:60)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.b$b$a.a(Unknown Source:2)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at j.a.a.a$a.a(:1)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at j.a.a.c.b(:2)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.h.a(Unknown Source:10)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at j.a.a.a.b(Unknown Source:7)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.h.a(Unknown Source:10)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.b$b.d(Unknown Source:68)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.b$b.a(Unknown Source:35)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.l.b(Unknown Source:12)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.h.a(Unknown Source:10)
2019-05-16 18:57:16.113 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.b.b(:2)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.h.a(Unknown Source:10)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.r.b(Unknown Source:11)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.h.a(Unknown Source:10)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.j.b(Unknown Source:11)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.h.a(Unknown Source:10)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.e.d.q$b.run(Unknown Source:8)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.k$a.run(Unknown Source:9)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at e.b.e.g.i.call(:1)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-05-16 18:57:16.114 16757-16824/com.fitphilia.treadmill.trainer W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-05-16 18:57:16.309 16757-16757/com.fitphilia.treadmill.trainer I/zygote64: Deoptimizing java.lang.String i.b.a.d.b.a(i.b.a.t) due to JIT inline cache

**Comment by JakeWharton** [comment]
It's not clear why you think RxAndroid is at fault nor is it clear what steps we could take here.

First and foremost you need the de-obfuscated trace to have any hope of figuring out what's going on. Second, RxAndroid is a very small library, and it's unlikely the problem lies inside of it. Third, evidenced by the fact that it works in debug but not production almost certainly makes it a configuration issue for your chosen code shrinker and not a library problem.

If you believe it to be a library problem, please provide a sample app that reproduces the failure so that we can debug it.

**Comment by iamkdblue** [comment]
@JakeWharton 
because I got an error here 
   ```
@Override
                               public void onError(Throwable e) {
                                   //error getting here
                                   Log.d("feed", "error " + e.getMessage());

                               }
```
