### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION -> observeOn(AndroidSchedulers.mainThread())

### ISSUE THREAD

**Issue by makhosravi** [ReactiveX/RxAndroid#569]
Hi
I was doing a very simple practice with rxjava v3.0.3 and rxandroid v3.0.0 and encountered a problem. Main problem was on this line :
.observeOn(AndroidSchedulers.mainThread());

When I launch the program it crashes but when I change the libraries to rxjava:2.2.10 and rxandroid:2.1.0 everything works fine. here is my code:

in onCreate:

        final Model model = new Model("1","some text");
        Observable<Model> observable = Observable.create(new ObservableOnSubscribe<Model>()
        {
            @Override
            public void subscribe(@NonNull ObservableEmitter<Model> emitter) throws Throwable
            {
                if (!emitter.isDisposed())
                {
                    emitter.onNext(model);
                    emitter.onComplete();
                }
            }
        })
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread());

        observable.subscribe(new Observer<Model>()
        {
            @Override
            public void onSubscribe(@NonNull Disposable d)
            {

            }

            @Override
            public void onNext(@NonNull Model model)
            {
                Log.e(TAG, "onNext: " + model.title);
            }

            @Override
            public void onError(@NonNull Throwable e)
            {

            }

            @Override
            public void onComplete()
            {

            }
        });

And here is logcat:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.od.makh.rx, PID: 5681
    java.lang.BootstrapMethodError: Exception from call site #1 bootstrap method
        at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.<clinit>(AndroidSchedulers.java:33)
        at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.mainThread(AndroidSchedulers.java:44)
        at com.od.makh.rx.MainActivity.onCreate(MainActivity.java:43)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: SOURCE_UNKNOWN.
        at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.<clinit>(AndroidSchedulers.java:33) 
        at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.mainThread(AndroidSchedulers.java:44) 
        at com.od.makh.rx.MainActivity.onCreate(MainActivity.java:43) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

I cannot find the problem here or what I'm missing.
I did it from a tutorial and did the exact same thing.
 tutorial -> rxandroid:3.0.0 & rxjava:3.0.0

Please help me on this matter.

**Comment by akarnokd** [comment]
Do you get a crash with 3.0.2? Also try clean and fresh build your project.

**Comment by makhosravi** [comment]
I just checked 3.0.0 and 3.0.3
and yes I cleaned my project 

but I`ll check it with 3.0.2
thanks

**Comment by makhosravi** [comment]
> Do you get a crash with 3.0.2? Also try clean and fresh build your project.

I tried with 3.0.2 and had the same problem
also cleaned and rebuild the project

**Comment by JakeWharton** [comment]
You must enable Java 8 in your application: https://developer.android.com/studio/write/java8-support

The bootstrap method for each lambda will be removed at compile-time and replaced with a proper class.

**Comment by makhosravi** [comment]
> You must enable Java 8 in your application: https://developer.android.com/studio/write/java8-support
> 
> The bootstrap method for each lambda will be removed at compile-time and replaced with a proper class.

thank a lot for your support
that`s the thing I was missing
