### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by 13man** [ReactiveX/RxAndroid#578]
# OkHttp Dispatcher(48197)

java.lang.NoSuchMethodError

No static method disposed()Lio/reactivex/rxjava3/disposables/Disposable; in class Lio/reactivex/rxjava3/disposables/Disposable; or its super classes (declaration of 'io.reactivex.rxjava3.disposables.Disposable' appears in base.apk!classes3.dex)

1 io.reactivex.rxjava3.android.schedulers.HandlerScheduler$HandlerWorker.schedule(HandlerScheduler.java:91)
--
2 io.reactivex.rxjava3.core.Scheduler$Worker.schedule(Scheduler.java:402)
3 io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.schedule(ObservableObserveOn.java:161)
4 io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.onComplete(ObservableObserveOn.java:139)
5 io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onComplete(ObservableSubscribeOn.java:68)
6 retrofit2.adapter.rxjava3.BodyObservable$BodyObserver.onComplete(BodyObservable.java:70)
7 retrofit2.adapter.rxjava3.CallEnqueueObservable$CallCallback.onResponse(CallEnqueueObservable.java:66)
8 retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
9 okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
10 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12 java.lang.Thread.run(Thread.java:929)

What is the problem and how to solve it ?

**Comment by Goooler** [comment]
What's your RxJava version ? The `io.reactivex.rxjava3.disposables.Disposable#disposed` should be here.

![image](https://user-images.githubusercontent.com/10363352/112923991-e6710380-9141-11eb-8d99-263b2232d9df.png)

**Comment by huihui4045** [comment]
我也是同样的问题

**Comment by huihui4045** [comment]
I have the same problem

**Comment by huihui4045** [comment]
Caused by: java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)
        at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.<clinit>(AndroidSchedulers.java:33)
        at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.from(AndroidSchedulers.java:55)

**Comment by JakeWharton** [comment]
That is not the same problem. You need to enable Java 8 support: https://developer.android.com/studio/write/java8-support#supported_features

**Comment by blankyn** [comment]
问题解决了吗

**Comment by Goooler** [comment]
> 问题解决了吗

```
android {
    ...
    // Configure only for each module that uses Java 8
    // language features (either in its source code or
    // through dependencies).
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    // For Kotlin projects
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```

**Comment by blankyn** [comment]
> > 问题解决了吗
> 
> ```
> android {
>     ...
>     // Configure only for each module that uses Java 8
>     // language features (either in its source code or
>     // through dependencies).
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
>     // For Kotlin projects
>     kotlinOptions {
>         jvmTarget = "1.8"
>     }
> }
> ```

我设置了，但是无效，依然还会报错

**Comment by Goooler** [comment]
@Blankyn 升级 AGP 看看，可能太旧了

**Comment by blankyn** [comment]
> @Blankyn 升级 AGP 看看，可能太旧了

我用的3.6.3版本

**Comment by blankyn** [comment]
> @Blankyn 升级 AGP 看看，可能太旧了

经过测试，as运行没这个问题，但是打包apk就有这个问题。rxandroid 用2.1.1的也可以，唯独升级后有问题

**Comment by 13man** [comment]
此处要改成:&nbsp;.addCallAdapterFactory(RxJava3CallAdapterFactory.createSynchronous())




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReactiveX/RxAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月13日(星期三) 下午2:06
***@***.***&gt;;
抄送:&nbsp;"自由 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReactiveX/RxAndroid] java.lang.NoSuchMethodError (#578)





  
@Blankyn 升级 AGP 看看，可能太旧了
  
经过测试，as运行没这个问题，但是打包apk就有这个问题。rxandroid 用2.1.1的也可以，唯独升级后有问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by blankyn** [comment]
> 此处要改成:&nbsp;.addCallAdapterFactory(RxJava3CallAdapterFactory.createSynchronous())
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ReactiveX/RxAndroid" ***@***.***&gt;; 发送时间:&nbsp;2021年10月13日(星期三) 下午2:06 ***@***.***&gt;; 抄送:&nbsp;"自由 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ReactiveX/RxAndroid] java.lang.NoSuchMethodError (#578) @Blankyn 升级 AGP 看看，可能太旧了 经过测试，as运行没这个问题，但是打包apk就有这个问题。rxandroid 用2.1.1的也可以，唯独升级后有问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没用的，安卓部分机器有问题，我测试过，目前发现两款机器

**Comment by 13man** [comment]
确认下依赖&nbsp;是否都是3系列
com.squareup.retrofit2:adapter-rxjava3:2.9.0io.reactivex.rxjava3:rxandroid:3.0.0io.reactivex.rxjava3:rxjava:3.0.0.addCallAdapterFactory(RxJava3CallAdapterFactory.createSynchronous())


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ReactiveX/RxAndroid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月5日(星期五) 上午10:18
***@***.***&gt;;
抄送:&nbsp;"自由 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ReactiveX/RxAndroid] java.lang.NoSuchMethodError (#578)





  
此处要改成:&nbsp;.addCallAdapterFactory(RxJava3CallAdapterFactory.createSynchronous())
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ReactiveX/RxAndroid" @.&gt;; 发送时间:&nbsp;2021年10月13日(星期三) 下午2:06 @.&gt;; 抄送:&nbsp;"自由 @.@.&gt;; 主题:&nbsp;Re: [ReactiveX/RxAndroid] java.lang.NoSuchMethodError (#578) @Blankyn 升级 AGP 看看，可能太旧了 经过测试，as运行没这个问题，但是打包apk就有这个问题。rxandroid 用2.1.1的也可以，唯独升级后有问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
没用的，安卓部分机器有问题，我测试过，目前发现两款机器
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hanlyjiang** [comment]
I had this problem too, and finally I found the problem.


**The scenario where the problem occurs is:**
- I have a library project and an app project, and I package the library project as an aar, and then introduce it into the app project. The library project uses the static method (disposed) of the Disposable interface of rxjava3.
- The problem only occurs when aar is introduced and the app project is packaged as an apk to manually install and run to the device. If you directly depend on the library project, or run it directly with AndroidStudio (whether it is aar dependency or project dependency), there is no problem.

**I found two ways to solve or circumvent this problem:**
1. Change the way to import aar。  

from:
```groovy
    implementation(name:"libs",ext: "aar")
``` 

to:    
```groovy
    implementation(files("libs/libs.aar"))
```

2. Add a property to `gradle.properties`
```properties
android.enableDexingArtifactTransform.desugaring=false
```
The cause of the problem lies in the process of desugaring. 
When you look at the Dex file in the apk, you can find that the Disposable interface of rxjava3 will be divided into two parts, one of which is `Disposable`, which contains the declarations of two interface methods, and the other is `Disposable$-CC` , which contains all static methods. Our code calls static methods through Disposable, so the correct situation should be that when the class in our aar is converted to dex, the call to the static method needs to be replaced with `Disposable$-CC.xxxx()`, but when we aar is imported with (name,ext) , AGP will not  do this for us. 

More specific reasons require us to study the behavior of AGP or D8

**Comment by KikilLove22** [comment]
android.enableDexingArtifactTransform.desugaring=false

**Comment by hsy719007146** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hsy719007146** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Vanesaa123** [comment]
.editorconfig

**Comment by hsy719007146** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Vanesaa123** [comment]
#591

**Comment by Vanesaa123** [comment]
[.editorconfig](.editorconfig) 

>  #``

> #591
