### ISSUE TITLE
RxAndroid 3.0.1 NPE in JVM unit tests

### ISSUE THREAD

**Issue by laalto** [ReactiveX/RxAndroid#594]
Setup: JVM based unit tests with `RxAndroidPlugins.setMainThreadSchedulerHandler { TestScheduler() }`. Code under test containing e.g. `observeOn(AndroidSchedulers.mainThread())`.

Working fine on RxAndroid 3.0.0.

Updating to RxAndroid 3.0.1 failing with NPE:

```
java.lang.ExceptionInInitializerError
	at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.lambda$static$0(AndroidSchedulers.java:33)
	at io.reactivex.rxjava3.android.plugins.RxAndroidPlugins.callRequireNonNull(RxAndroidPlugins.java:85)
	at io.reactivex.rxjava3.android.plugins.RxAndroidPlugins.initMainThreadScheduler(RxAndroidPlugins.java:39)
	at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.<clinit>(AndroidSchedulers.java:33)
...
Caused by: java.lang.NullPointerException: looper == null
	at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.from(AndroidSchedulers.java:66)
	at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers.from(AndroidSchedulers.java:54)
	at io.reactivex.rxjava3.android.schedulers.AndroidSchedulers$MainHolder.<clinit>(AndroidSchedulers.java:29)
```

Quick peek at commit history suggests this might be caused by #577

**Comment by JakeWharton** [comment]
Ok yep. Will look.
